VipraTask/contactbook/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
# from feed.api_views import CreateContactBookApiView

from feed.views import add_contact, contactBook_detail, contactBook_list, edit_contact, home_page, info_contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home_page"),
    path('add_contact/', add_contact , name="add_contact"),
    path('info_contact/<int:pk>', info_contact, name="info_contact"),
    path('edit_contact/<int:pk>', edit_contact, name="edit_contact"),
    path('contacts/', contactBook_list, name="contactBook_list"),
    path('contacts/<int:pk>', contactBook_detail, name="contactBook_detail"),
]

VipraTask/feed/models.py
from django.db import models
from django.core.validators import RegexValidator

class ContactBook(models.Model):
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")

    first_name = models.CharField(max_length=30, verbose_name = "first name")
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    phoneNumber = models.CharField(validators= [phoneNumberRegex], max_length=10, unique=True, verbose_name = "Phone Number")

    def __str__(self):
        return  self.first_name + " " + self.last_name
    

VipraTask/feed/views.py
import json
from django.shortcuts import get_object_or_404, render
from django.contrib import messages


from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser

from feed.models import ContactBook
from feed.serializers import ContactBookSerializer

@csrf_exempt
def contactBook_list(request):
    if request.method == "GET":
        contactBook = ContactBook.objects.all()
        serializer = ContactBookSerializer(contactBook, many=True)
        return JsonResponse(serializer.data, safe=False)

    elif request.method == "POST":
        data = JSONParser().parse(request)
        serializer = ContactBookSerializer(data=data)

        if serializer.is_valid():
            serializer.save()
            messages.add_message(request, messages.SUCCESS, 'Your contact was successfully added.')
            return JsonResponse(serializer.data, status=200)
        return JsonResponse(serializer.errors, status=400)

@csrf_exempt
def contactBook_detail(request, pk):
    try:
        contactBook = ContactBook.objects.get(pk=pk)
    except ContactBook.DoesNotExist:
        return HttpResponse(status=404)
    
    if request.method == "GET":
        serializer = ContactBookSerializer(contactBook)
        return JsonResponse(serializer.data)

    elif request.method == "PUT":
        data = JSONParser().parse(request)
        serializer = ContactBookSerializer(contactBook, data=data)
        if serializer.is_valid():
            serializer.save()
            messages.add_message(request, messages.INFO, 'Your contact was successfully edited.')
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=400)
    elif request.method == "DELETE":
        contactBook.delete()
        messages.add_message(request, messages.WARNING, 'Your contact was successfully deleted.')
        return HttpResponse(status=204)


def home_page(request):
    template = "homepage.html"
    contacts = ContactBook.objects.all()
    context = {
        'contacts': contacts,
    }
    return render (request, template, context)
    
def info_contact(request, pk):
    template = "info_contact.html"
    get_contact = ContactBook.objects.get(id=pk)
    context = {
        'get_contact': get_contact,
    }
    return render (request, template, context)

def add_contact(request):
    template = "add_contact.html"
    form = ContactBookSerializer()
    context ={
        'form': form,
    }
    return render(request, template, context)

def edit_contact(request, pk):
    template = "edit_contact.html"
    contact = get_object_or_404(ContactBook, id=pk)
    context = {
        'contact':contact,
    }
    return render (request, template, context)

VipraTask/contactbook/templates/add_contact.html
{% extends 'nav.html' %}

{% block title %}Add contact{% endblock %}

{% block content %}
<div class="mt-4 flex justify-center ">
    <a class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200" href="{% url 'add_contact' %}">Add Contact</a>
</div>

<div class="flex justify-center ">
    <div class="p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg w-max ">        
        <form method = "POST" action ="" class="success">
            {% csrf_token %}
            
            <p >
                <label class="text-xl" for="id_first_name">First name:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 fn-add" type="text" name="first_name" maxlength="30" required id="id_first_name" value="{{ form.first_name.value|default_if_none:''}}">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_last_name">Last name:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 ln-add" type="text" name="last_name" maxlength="30" required id="id_last_name" value="{{ form.last_name.value|default_if_none:''}}">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_email">Email:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 email-add" type="email" name="email" maxlength="100" required id="id_email" value="{{ form.email.value|default_if_none:''}}">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_phoneNumber">Phone Number:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 pn-add" type="text" name="phoneNumber" maxlength="10" required id="id_phoneNumber" value="{{ form.phoneNumber.value|default_if_none:''}}">
            </p>  

            <p class="flex justify-center">
                <button class="font-bold border-2 border-solid border-gray-400 rounded-lg p-2 text-2xl bg-yellow-400 js-submit" type="submit" data-url="{% url 'contactBook_list' %}">Submit</button>
            </p> 
        </form>
    </div>
</div>
{% endblock  %}

VipraTask/contactbook/templates/edit_contact.html
{% extends 'nav.html' %}

{% block title %}Edit contact{% endblock %}

{% block content %}
<div class="mt-8 flex justify-center ">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">Edit Contact</div>
</div>
<div class="flex justify-center">
    <div class="p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg w-max">
        <form method = "POST" action ="">
            {% csrf_token %}
             <p class="flex flex-col my-4">
                <label class="text-xl" for="id_first_name">First name:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 fn-edit" type="text" name="first_name" value="{{contact.first_name}}" maxlength="30" required id="id_first_name">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_last_name">Last name:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 ln-edit" type="text" name="last_name" value="{{contact.last_name}}" maxlength="30" required id="id_last_name">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_email">Email:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-lg font-medium border-2 border-solid border-gray-400 email-edit" type="email" name="email" value="{{contact.email}}" maxlength="100" required id="id_email">
            </p>
            <p class="flex flex-col my-4">
                <label class="text-xl" for="id_phoneNumber">Phone Number:</label>
                <input class="w-full px-10 py-1 text-center rounded-lg text-xl font-medium border-2 border-solid border-gray-400 pn-edit" type="text" name="phoneNumber" value="{{contact.phoneNumber}}" maxlength="10" required id="id_phoneNumber">
            </p>

            <p class="flex justify-center">
                <button class="font-bold border-2 border-solid border-gray-400 rounded-lg p-2 text-2xl bg-yellow-400 js-edit" type="submit" data-url="{% url 'contactBook_detail' contact.id %}">Submit</button>
            </p> 
            
            <p class="w-max text-xl mt-4 text-red-500 errors-edit">
            
            </p>


        </form>
    
    </div>
</div>
{% endblock  %}

VipraTask/contactbook/templates/homepage.html
{% extends 'nav.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}> 
            {% if message.tags == "success" %}
                <div class="flex font-bold text-xl text-white py-4 justify-center bg-green-500">{{ message }}</div>
            {% elif message.tags == "info" %}
                <div class="flex font-bold text-xl text-white py-4 justify-center bg-yellow-500">{{ message }}</div>
            {% elif message.tags == "warning" %}
                <div class="flex font-bold text-xl text-white py-4 justify-center bg-red-500">{{ message }}</div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
{% endif %} 

<div>
    <div class="mt-4 flex justify-center ">
        <a class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200" href="{% url 'add_contact' %}">Add Contact</a>
    </div>
    <div class="flex flex-wrap p-2 justify-evenly">
        {% for contact in contacts %}
                <div class="inline-block p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg">
                    <div class="flex flex-col items-center p-2 ">
                        <span class="text-blue-500 underline">&bull; First name:</span>
                        <span>{{contact.first_name}}</span>
                    </div>
                    <div class="flex flex-col items-center p-2">
                        <span class="text-blue-500 underline">&bull; Last name:</span>
                        <span>{{contact.last_name}}</span>
                    </div>
                    <div class="flex flex-col items-center p-2 ">
                        <span class="text-blue-500 underline">&bull; Email:</span>
                        <span>{{contact.email}}</span>
                    </div>
                    <div class="flex flex-col items-center p-2">
                        <span class="text-blue-500 underline">&bull; Phone Number:</span>
                        <span>{{contact.phoneNumber}}</span>
                    </div>
                    <div class="flex justify-evenly p-2">
                        <a href="{% url 'edit_contact' contact.id %}" class="border-2 border-solid border-gray-400 rounded-lg p-1 text-black bg-yellow-400 ">Edit</a>
                        <a href="{% url 'info_contact' contact.id %}" class="border-2 border-solid border-gray-400 rounded-lg p-1 bg-green-400">Info</a>
                        <a href="{% url 'contactBook_detail' contact.id %}" class="border-2 border-solid border-gray-400 rounded-lg p-1 bg-red-400 js-delete" data-url="{% url 'contactBook_detail' contact.id %}">Delete</a>
                    </div>
                </div>
        {% endfor %}
    </div>

    <div class="mb-4 flex justify-center ">
        <a class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200" href="{% url 'add_contact' %}">Add Contact</a>
    </div>
</div>
{% endblock  %}

VipraTask/contactbook/templates/info_contact.html
{% extends 'nav.html' %}

{% block title %}Info contact{% endblock %}

{% block content %}
<div class="mt-8 flex justify-center ">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">Info Contact</div>
</div>
<div class="flex justify-center">
    <div class="inline-block p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg text-xl">
        <div class="flex flex-col items-center p-2 ">
            <span class="text-blue-500 underline">&bull; First name:</span>
            <span>{{get_contact.first_name}}</span>
        </div>
        <div class="flex flex-col items-center p-2">
            <span class="text-blue-500 underline">&bull; Last name:</span>
            <span>{{get_contact.last_name}}</span>
        </div>
        <div class="flex flex-col items-center p-2 ">
            <span class="text-blue-500 underline">&bull; Email:</span>
            <span>{{get_contact.email}}</span>
        </div>
        <div class="flex flex-col items-center p-2">
            <span class="text-blue-500 underline">&bull; Phone Number:</span>
            <span>{{get_contact.phoneNumber}}</span>
        </div>
        <div class="flex justify-evenly p-2">
            <a href="{% url 'edit_contact' get_contact.id %}" class="border-2 border-solid border-gray-400 rounded-lg p-1 text-black bg-yellow-400 ">Edit</a>
            <a href="{% url 'contactBook_detail' get_contact.id %}" class="border-2 border-solid border-gray-400 rounded-lg p-1 bg-red-400 js-delete" data-url="{% url 'contactBook_detail' get_contact.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock  %}

VipraTask/contactbook/templates/nav.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="bg-red-50">

    <nav class="bg-indigo-900 flex justify-start border-b-2 border-gray-800 p-2 font-semibold text-white">
        <a class="no-underline text-white " href="{% url 'home_page' %}"><h1 class="text-3xl font-extrabold">Contact Book</h1></a>
    </nav>

    {% block content %}
    
    {% endblock  %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>