GESCI/GESCI/urls.py
from django.contrib import admin
from django.urls import path
from Users.views import HomePage, UserEditView, PasswordChange, Classes, ProfileDetailView, edit_post, course_detail, show_course_detail,  users_profile, add_post, delete_post, students_in_group, search_course 
from django.conf.urls import include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name="home"),
    path("profile/", UserEditView.as_view(), name="detail"),
    path("classes/<str:name>/", Classes.as_view(), name="classes"),
    path("password/", PasswordChange.as_view(), name="password_change"),
    path("my_profile/", ProfileDetailView.as_view(), name="my_profile"),
    path("course_detail/<int:pk>", show_course_detail, name="course_detail"),
    path("course/", course_detail, name="student_courses"),
    path("form_course/<int:pk>", edit_post, name="form_course"),
    path("users_profile/<int:pk>", users_profile, name="users_profile"),
    path("add_info/<int:pk>", add_post, name="add_post"),
    path("delete_info/<int:pk>", delete_post, name="delete_post"),
    path("group/<int:gn>", students_in_group, name="students_in_group"),
    path("search_course/<x>", search_course, name="search_course"),
    path('', include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GESCI/Users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from .models import User, Post

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')


class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=25, widget=forms.PasswordInput(attrs={'class':'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(max_length=25, widget=forms.PasswordInput(attrs={'class':'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(max_length=25, widget=forms.PasswordInput(attrs={'class':'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

class ClassForm(forms.ModelForm):
    text =  forms.CharField(widget=forms.Textarea(attrs={'style':'border:2px solid black','class':'form-control',"rows":20, "cols":50}))
    class Meta:
        model = Post
        fields = ('text', 'file')

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('teacher', 'course', 'group', 'text', 'file',)

GESCI/GESCI/templates/add_post.html
{% extends 'homepage.html' %}

{% block title %} Add Info {% endblock title %}

{% block content %}
    {% if request.user.is_authenticated == True %}
    <div class="mt-20">
        {% if user.is_teacher %}
            <div class="flex justify-center" >    
                <div class="rounded-lg w-96 h-full p-10 bg-green-300 shadow-xl" style="border: 1px solid black">
                    <form enctype="multipart/form-data" method="POST" action="">
                        {% csrf_token %}
                        {% comment %} {{form.as_p}} {% endcomment %}
                        <p>
                            <label for="form.teacher" >Teacher:</label> 
                            <select name={{form.teacher.name}}  required="" id="form.teacher">
                                {% for f in form.teacher.field.choices %}
                                    {% if f.1 == course_id.teacher.user.username %}
                                        <option value="{{f.0}}" >{{f.1}}</option> 
                                    {% endif %}
                                {% endfor %}
                            </select> 
                        </p> 
                        
                        <p>
                            <label for="form.course">Course:</label> 
                            <select name="{{form.course.name}}" required="" id="form.course">
                                {% for f in form.course.field.choices %}
                                    {% if f.1 == course_id.course.name %}
                                        <option value="{{f.0}}" >{{f.1}}</option> 
                                    {% endif %}
                                {% endfor %}
                            </select> 
                        </p>

                        <p>
                            <label for="form.group">Group:</label>
                            <select name="{{form.group.name}}" required="" id="form.group">
                                {% for f in form.group.field.choices %}
                                    {% if f.1 == course_id.group.number %}
                                        <option value="{{f.0}}" >{{f.1}}</option> 
                                    {% endif %}
                                {% endfor %}
                            </select> 
                        </p>

                        <p>
                            <label for="">Text:</label> 
                            {{form.text}}
                        </p>

                        <p>
                            <label for="">File:</label> 
                            {{form.file}}
                        </p>  

                        <button type="sumbit" class="btn btn-lg btn-success w-80 h-14"> 
                            <span class="text-3xl">
                                Post
                            </span>
                        </button> 
                    </form>

                    {% if form.errors %}
                        {{form.errors}}
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
    {% endif %}
{% endblock content %}

GESCI/GESCI/templates/classes.html
{% extends 'homepage.html' %}

{% block title %} Courses {% endblock title %}

{% block content %}

<div class="mt-20">
    <div class="border-b border-grey-light p-4 bg-grey-lighter py-8">
      <div class="bg-white mx-auto max-w-sm shadow-lg rounded-lg overflow-hidden">
        <div class="sm:flex sm:items-center px-2 py-4">
          <div class="flex-grow">
            <h3 class="font-normal px-2 py-3 leading-tight">Group: {{group.number}}</h3>
            <div class="w-full">
            {% for sg in studentGroup %}
                {% if sg.group == group %}  
                    <div class="flex cursor-pointer my-1 hover:bg-blue-lightest rounded">
                        <div class="w-8 h-10 text-center py-1">
                            <p class="text-3xl p-0 text-green-dark">&bull;</p>
                        </div>
                        <div class="w-4/5 h-10 py-3 px-1">
                            <a class="ml-1 text-indigo-600 hover:underline" href="{% url 'users_profile' sg.student.user.id%}">
                                {{sg.student.user.first_name}} {{sg.student.user.last_name}}
                            </a> 
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

GESCI/GESCI/templates/detail.html
{% extends 'homepage.html' %}

{% block title %} {{user.username}} {% endblock title %}

{% block content %}

    <div class="mt-20">
        <div class="flex justify-center">
            <h2 class="flex justify-center w-1/4 text-4xl mb-2 font-semibold font-heading font-semibold py-3 rounded-lg bg-blue-400" style="border: 1px solid black">Edit profile</h2>
        </div>
        <div class="flex justify-center" >    
            <div class="rounded-lg w-96 h-96 p-10 bg-blue-400 shadow-xl" style="border: 1px solid black">
                <form method="POST" action="" class="login">
                    {% csrf_token %}
                    <p>
                        <label for="id_first_name">First name:</label> 
                        <input type="text" name="first_name" value="{{user.first_name}}" class="form-control" maxlength="25" required="" id="id_first_name">
                    </p>
                    <p>
                        <label for="id_last_name">Last name:</label> 
                        <input type="text" name="last_name" value="{{user.last_name}}" class="form-control" maxlength="25" required="" id="id_last_name">
                    </p>
                    <p>
                        <label for="id_email">Email:</label> 
                        <input type="email" name="email" value="{{user.email}}" class="form-control" required="" id="id_email">
                    </p>
                    <p>
                        <label for="id_password">Password:</label> 
                        <a href="{% url 'password_change' %}" class="text-red-600">Change password</a>

                    </p>
                    <button type="sumbit" style="border: 1px solid black" class="primaryAction btn btn-lg btn-warning form-control"> Update Profile </button>
            </div>
        </div>
    </div>
{% endblock content %}

GESCI/GESCI/templates/home.html
{% extends 'homepage.html' %}

{% block title %} Courses {% endblock title %}

{% block content %}
    <div style="margin:0;">    
       <!-- This is an example component -->
        <div class="w-full h-screen bg-center bg-no-repeat bg-cover" style="background-image: url('https://images.unsplash.com/photo-1609342475528-dd7d93e8311e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=676&q=80');">
            <div class="w-full h-screen bg-opacity-50 bg-black flex justify-center items-center">
                <div class="mx-4 text-center text-white">
                {% if request.user.is_authenticated %}
                    {% if user.is_student %}
                        <h1 class="font-bold text-6xl mb-4">Welcome, student!</h1>
                    {% elif user.is_teacher %}
                        <h1 class="font-bold text-6xl mb-4">Welcome, teacher!</h1>
                    {% elif user.is_admin %}
                        <h1 class="font-bold text-6xl mb-4">Welcome, admin!</h1>
                    {% endif %}
                    <h2 class="font-bold text-3xl mb-12">{{user.first_name}} {{user.last_name}}</h2>
                    <div>
                            <a href="{% url 'student_courses' %}" class="bg-blue-500 rounded-md font-extrabold text-white text-center px-4 py-3 transition duration-300 ease-in-out  text-xl   hover:bg-blue-600 mr-2">
                                See your courses!
                            </a>
                {% else %}
                        <h1 class="font-bold text-6xl mb-4">Welcome!</h1>
                        <h3>Hello, if you are here it means that you want to test this site. Here you have two accounts: one for the teacher and one for the student. :</h3>
                        <br/>
                        <h4>Teacher:</h4>
                        <ul>
                            <li>email: teacher@email.com</li>
                            <li>password: Parola123@</li>
                        </ul>
                        <h4>Student:</h4>
                        <ul>
                            <li>email: student@email.com<li>
                            <li>password: Parola123@</li>
                        </ul>
                        <br/>
                        <a href="{% url 'account_login' %}" class="bg-red-500 rounded-md font-extrabold text-white text-center px-3 py-3 transition duration-300 ease-in-out hover:bg-red-600 ml-2 text-xl" >
                            Log in!
                        </a>
                {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

GESCI/GESCI/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title> {% block title %}Home{% endblock title %} </title>
</head>
<body>
     <!-- component -->
    <div class="min-h-screen  flex flex-row bg-gray-100">
      <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
        <div class="flex items-center justify-center h-20 shadow-md">
          <h1 class="text-3xl uppercase text-indigo-500">GESCI</h1>
        </div>
        <ul class="flex flex-col py-4">
            <li>
              <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200  text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
                <span class="text-sm font-medium">Home</span>
              </a>
            </li>
          {%if request.user.is_authenticated%}
            <li>
              <a href="{% url 'student_courses' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform   ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bxs-book"></i></span>
                <span class="text-sm font-medium">Courses</span>
              </a>
            </li>

            <li>
              <a href="{% url 'my_profile' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in  duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bxs-user-account"></i></span>
                <span class="text-sm font-medium">Profile</span>
              </a>
            </li>
            <li>
              <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform  ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
                <span class="text-sm font-medium">Logout</span>
              </a>
            </li>
          {% else %}
              <li>
                <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform   ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
                  <span class="text-sm font-medium">Login</span>
                </a>
              </li>
          {% endif %}
        </ul>
      </div> 



      <div class="w-full">
            {% block content %}
    
            {% endblock %}
      </div>

    </div>

{% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>      
<script src="{% static 'js/main.js' %}"></script> {% endcomment %}
</body>
</html>

GESCI/GESCI/templates/password_change.html
{% extends 'homepage.html' %}

{% block title %} Change Password {% endblock title %}

{% block content %}

    <div class="mt-20">
        <div class="flex justify-center">
            <h2 class="flex justify-center w-1/4 text-4xl mb-2 font-semibold font-heading font-semibold py-3 rounded-lg bg-yellow-300" style="border: 1px solid black">Change Password</h2>
        </div>

        <div class="flex justify-center" >    
            <div class="rounded-lg w-96 h-full p-10 bg-yellow-300 shadow-xl" style="border: 1px solid black">
                <form method="POST" action=""  class="login">
                    {% csrf_token %}
                    <p>
                        <label for="id_old_password">Old password:</label> 
                        <input type="password" name="old_password" class="form-control" maxlength="25" required="" id="id_old_password">
                    </p>
                    <ul class="mb-4 list-inside list-disc">
                        <li>Your password can’t be too similar to your other personal information.</li>

                        <li>Your password must contain at least 8 characters.</li>

                        <li>Your password can’t be a commonly used password.</li>

                        <li>Your password can’t be entirely numeric.</li>
                    </ul>
                    <p>
                        <label for="id_new_password1">New password:</label> 
                        <input type="password" name="new_password1" class="form-control" maxlength="25" required="" id="id_new_password1">
                    </p>
                    <p>
                        <label for="id_new_password2">New password (again):</label> 
                        <input type="password" name="new_password2" class="form-control" maxlength="25" required="" id="id_new_password2">
                    </p>
                    <button type="sumbit" style="border: 1px solid black"  class="primaryAction btn btn-lg btn-success form-control"> Change </button>
                </form>
                <br>

            </div>
        </div>
    </div>
    
{% endblock content %}

GESCI/GESCI/templates/profile.html
{% extends 'homepage.html' %}

{% block title %} {{user.username}} {% endblock title %}

{% block content %}

    <div class="mt-20">
        {% for item in items %}
             {% if request.user.id == item.id %}
                <div class="flex items-center justify-center">
                    <div class="">
                        <div class="bg-yellow-100 shadow-xl rounded-lg py-3 h-96 w-96" style="border:1px solid black">
                            <div class="p-2 mt-6">
                                <h2 class="text-center text-3xl text-gray-900 leading-8">My profile:</h2>
                                <table class="text-base my-3">
                                    <tbody>
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">Rang:</td>
                                            {% if item.is_student %}
                                                <td class="px-2 py-2">Student</td>
                                            
                                            {% elif item.is_teacher %}
                                                <td class="px-2 py-2">Teacher</td>

                                            {% elif item.is_admin %}
                                                <td class="px-2 py-2">Admin</td>
                                            {% endif %}
                                        </tr>
                                        {% if item.is_student %}
                                            {% for group in groups  %}
                                                {% if item.username == group.student.user.username %}
                                                    <tr>
                                                        <td class="px-2 py-2 text-gray-500 font-semibold">Group:</td>
                                                        <td class="px-2 py-2">{{group.group.number}}</td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">First name:</td>
                                            <td class="px-2 py-2">{{item.first_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">Last name:</td>
                                            <td class="px-2 py-2">{{item.last_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">Email:</td>
                                            <td class="px-2 py-2">{{item.email}}</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <div class="text-center my-3">
                                    <a class="text-xs text-indigo-500 italic hover:underline hover:text-indigo-600 font-medium" href="{% url 'detail' %}">
                                        <button type="sumbit" style="border: 1px solid black" class="btn btn-lg btn-primary"> Edit Profile </button>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
             {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

GESCI/GESCI/templates/profile_detail.html
{% extends 'homepage.html' %}

{% block title %} Courses {% endblock title %}

{% block content %}

    <div style="margin:20px;">
        {% if request.user.is_authenticated == True %}
    
            <div>
                <h2 class="underline flex flex-col mb-5"> 
                            {{post.course.name}}
                </h2>
            </div>

            <h4 class= " px-5 mb-5"> 
                <div>Teacher: {{post.teacher.user.first_name}} {{post.teacher.user.last_name}}</div> 
            </h4>

            <div class= "mb-5" >
                <h2 class="underline mb-5">Information:</h2>
                <p class="ml-2 text-2xl text-justify px-5">{{post.text}}</p>
            </div>
        
        {% endif %}

        {% if user.is_teacher == True %}
                <a href="{% url 'form_course' post.id %}">
                    <button class="primaryAction btn btn-lg btn-success" type="submit">Edit</button>
                </a>
        {% endif %}
    </div>    
{% endblock content%}

GESCI/GESCI/templates/users_profile.html
{% extends 'homepage.html' %}

{% block title %} User's Profile {% endblock title %}

{% block content %}

    <div class="mt-20">
         {% if user.is_authenticated %}
            <div class="flex items-center justify-center">
                <div class="">
                    <div class="bg-yellow-100 shadow-xl rounded-lg py-3 h-96 w-96" style="border:1px solid black">
                        <div class="p-2 mt-6">
                            <h2 class="text-center text-3xl text-gray-900 leading-8">User's Profile:</h2>
                            <table class="text-base mt-3">
                                <div class="mt-5">
                                    <tbody>
                                    {% for u in users %}
                                        {% if u.is_teacher == True and u.id == post.id%}
                                            <tr>
                                                <td class="px-2 py-2 text-gray-500 font-semibold">Courses:</td>
                                                <td class="pr-2 py-2">
                                                    {% for teacher in teachers %}
                                                        {% if post.id == teacher.teacher.user.id %}
                                                            <div><ul class="m-0 list-disc"><li>{{teacher.course.name}}</li></ul></div>
                                                        {% endif %}
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">First name:</td>
                                            <td class="px-2 py-2">{{post.first_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">Last name:</td>
                                            <td class="px-2 py-2">{{post.last_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="px-2 py-2 text-gray-500 font-semibold">Email:</td>
                                            <td class="px-2 py-2">{{post.email}}</td>
                                        </tr>
                                    </tbody>
                                </div>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
         {% endif %}
    </div>
{% endblock content %}