ChatOnline/Chat/urls.py
from django.contrib import admin
from django.urls import path
from feed.views import HomePage, Home, get_search, search_user, add_friend, chat_messages, get_message, see_profile
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_search, name="homePage"),
    path("search_user/<str:text>", search_user, name="search_user"),
    path("search_user/<str:username>/add", add_friend, name="add_friend"),
    # path("search_user/<str:username>", change_text, name="change_text"),
    # path('home/', Home.as_view(), name="home"),
    path('chat/<int:pk>', chat_messages, name = "chat_messages"),
    path('chat/<int:pk>/data', get_message, name = "get_message"),
    path('see_profile/<int:pk>', see_profile, name = "see_profile"),
    path('', include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChatOnline/feed/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class FriendList(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="User1")
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="User2")
    
    class Meta:
        unique_together=[['user1', 'user2']]

    def __str__(self):
        return  self.user1.username    + '-' + self.user2.username    

class Chat(models.Model):
    friendship = models.ForeignKey(FriendList, on_delete=models.CASCADE, related_name="friendship")
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    date = models.DateTimeField(default=datetime.now, blank=True)
    text = models.TextField(null=True, blank=False)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return str(self.id) + '-' + self.friendship.user1.username    + '-' + self.friendship.user2.username + '-' + self.sender.username   

class Room(models.Model):
    friendship1 = models.ForeignKey(FriendList, on_delete=models.CASCADE, related_name="friendship1")
    friendship2 = models.ForeignKey(FriendList, on_delete=models.CASCADE, related_name="friendship2")

    class Meta:
        unique_together=[['friendship1', 'friendship2']]

    def __str__(self):
        return str(self.id) + '-' + self.friendship1.user1.username    + '-' + self.friendship1.user2.username + '-' + self.friendship2.user1.username    + '-' + self.friendship2.user2.username    

ChatOnline/feed/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from .models import User, Chat


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ('friendship', 'sender', 'text', 'file',)

ChatOnline/feed/views.py
from django import template
from feed.models import FriendList, Chat, Room
from django.http.response import FileResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, DetailView, ListView
from django.contrib.auth.models import User
from itertools import chain
from datetime import datetime
from django.shortcuts import get_object_or_404
from .forms import AddPostForm
class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "homepage.html"

class Home(TemplateView):
    http_method_names = ["get"]
    template_name = "home.html"

def get_search(request):
    template = "home.html"
    if request.method == "POST":
        search_user = request.POST['search']
        return redirect('/search_user/' + search_user)

    my_friends = FriendList.objects.none()
    room_chat = Room.objects.none()
    if request.user.is_authenticated:
        my_friends = FriendList.objects.filter(user1 = request.user)

        for mf in my_friends:
            if FriendList.objects.filter(user1 = mf.user2, user2 = request.user).exists():
                mf2 = FriendList.objects.get(user1 = mf.user2, user2 = request.user)
                if Room.objects.filter(friendship1 = mf, friendship2 = mf2).exists() == False:
                    Room.objects.create(friendship1 = mf, friendship2 = mf2)

        room_chat = Room.objects.filter(friendship1__user1 = request.user)
        # print(room_chat[0])
    context = {
        'my_friends':my_friends,
        'room_chat':room_chat,
    }

    return render(request, template, context)

def chat_messages(request, pk):
    try:
        if request.method == "POST":
            search_user = request.POST['search']
            return redirect('/search_user/' + search_user)
    except Exception as e:
        pass

    template = "chat_messages.html"
    room_chat = Room.objects.get(id = pk)

    my_chat_friend1 = Chat.objects.filter(friendship = room_chat.friendship1)
    my_chat_friend2 = Chat.objects.filter(friendship = room_chat.friendship2)

    my_chat_friend = my_chat_friend1|my_chat_friend2
    my_chat_friend = my_chat_friend.order_by("-date")

    if request.method == "POST":
        form = AddPostForm(request.POST or None, request.FILES or None)
        try:
            if form.is_valid():
                form.save()
                # messages.add_message(request, messages.SUCCESS, "Info Added!")
                return redirect('/chat/'+ str(pk))
        except Exception as e:
                # messages.Warning(request, "Your post was not saved due to an error {}".format(e))
                pass
    else:
        form = AddPostForm()

    context = {
        'form': form,
        'room_chat': room_chat,
        'my_chat_friend': my_chat_friend, 
    }
    return render(request, template, context)

def get_message (request, pk):
    room_chat = Room.objects.get(id = pk)

    my_chat_friend1 = Chat.objects.filter(friendship = room_chat.friendship1)
    my_chat_friend2 = Chat.objects.filter(friendship = room_chat.friendship2)

    my_chat_friend = my_chat_friend1|my_chat_friend2
    my_chat_friend = my_chat_friend.order_by("date")
    user = request.user.id

    if request.user.username == room_chat.friendship1.user1.username:
        sender = room_chat.friendship1.user2.username

    return JsonResponse({
        "messages": list(my_chat_friend.values()),
        "user": user,
        "pk": pk,
        "sender": sender,
    })

def see_profile(request, pk):
    try:
        if request.method == "POST":
            search_user = request.POST['search']
            return redirect('/search_user/' + search_user)
    except Exception as e:
        pass
    template = "profile.html"
    profile = get_object_or_404(User, id=pk)
    you_add = FriendList.objects.filter(user1 = request.user, user2=profile).exists()
    context = {
        'profile': profile,
        'you_add': you_add,
    }
    return render(request, template, context)

def search_user(request, text):
    template = "search_user.html"
    if request.method == "POST":
        search_user = request.POST['search']
        return redirect('/search_user/' + search_user)

    user = User.objects.filter(username__contains=text) 
    fname = User.objects.filter(first_name__contains=text) 
    lname = User.objects.filter(last_name__contains=text)

    users = user|fname|lname

    query_friend_list = Room.objects.none()
    for u in users:
        fl = Room.objects.filter(friendship1__user1 = request.user, friendship1__user2  = u, friendship2__user1 = u, friendship2__user2 = request.user)
        query_friend_list = query_friend_list|fl
    
    context = {
        'users': users,
        'text': text,
        'query_friend_list': query_friend_list,
    }   
    return render(request, template, context)

def add_friend(request, username):
    data = request.POST.dict()
    if "action" not in data or "username" not in data:
        return HttpResponseBadRequest("Missing data")

    try:
        other_user = User.objects.get(username = data['username'])
    except User.DoesNotExist:
        return HttpResponseBadRequest("Missing user")

    if data['action'] == "Add Friend":
        follower = FriendList.objects.get_or_create(
            user1 = request.user,
            user2 = other_user,
        )
    else:
        try:
            follower = FriendList.objects.get(
                user1 = request.user,
                user2 = other_user,
            )
        except FriendList.DoesNotExist:
            follower = None

        if follower:
            follower.delete()

    return JsonResponse({
        'succes':True,
        'wording': "Unfriend" if data['action'] == "Add Friend" else "Add Friend",
    })

    

ChatOnline/Chat/templates/chat_messages.html
{% extends 'home.html' %}
{% load static %}
    {% block title %} 
    Chat - 
    {% if   room_chat.friendship1.user1 == request.user %}
    {{room_chat.friendship1.user2.first_name}} {{room_chat.friendship1.user2.last_name}} {{room_chat.friendship1.user2.username}}     
    {% elif room_chat.friendship1.user2 == request.user %}
    {{room_chat.friendship1.user1.first_name}} {{room_chat.friendship1.user1.last_name}} {{room_chat.friendship1.user1.username}}         
    {% endif %}
    {% endblock title %}
<style>
.scrollbar-w-2::-webkit-scrollbar {
  width: 0.25rem;
  height: 0.25rem;
}

.scrollbar-track-blue-lighter::-webkit-scrollbar-track {
  --bg-opacity: 1;
  background-color: #f7fafc;
  background-color: rgba(247, 250, 252, var(--bg-opacity));
}

.scrollbar-thumb-blue::-webkit-scrollbar-thumb {
  --bg-opacity: 1;
  background-color: #edf2f7;
  background-color: rgba(237, 242, 247, var(--bg-opacity));
}

.scrollbar-thumb-rounded::-webkit-scrollbar-thumb {
  border-radius: 0.25rem;
}
</style> 
{% comment %} Credits: https://tailwindcomponents.com/component/chat {% endcomment %}
{% block content %}
<div class="flex flex-col clickFocus" style="width: 100%;">
    <div class="flex  items-center space-x-4 " >
         <img src="https://static.wikia.nocookie.net/caramella-girls/images/9/99/Blankpfp.png/revision/latest?cb=20190122015011" alt="" class="w-10 sm:w-16 h-10 sm:h-16 rounded-full m-2">
        <div class="flex flex-col leading-tight">
            <div class="text-2xl mt-1 flex items-center">
                {% if   room_chat.friendship1.user1 == request.user %}
                    <a  class="no-underline text-gray-900" href = "{% url 'see_profile' room_chat.friendship1.user2.id %}" >
                        <div class="flex bg-gray-100 p-4 w-72 space-x-4 rounded-lg">
                                {{room_chat.friendship1.user2.first_name}} {{room_chat.friendship1.user2.last_name}} {{room_chat.friendship1.user2.username}}
                        </div>
                    </a>
                {% elif room_chat.friendship1.user2 == request.user %}
                    <a href = "{% url 'see_profile' room_chat.friendship1.user2.id %}" >
                        <div class="flex bg-gray-100 p-4 w-72 space-x-4 rounded-lg">
                            {{room_chat.friendship1.user1.first_name}} {{room_chat.friendship1.user1.last_name}} {{room_chat.friendship1.user1.username}}
                        </div>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %} 
            <p style="display: none;">
                <label for="id_friendship">Friendship:</label> 
                <select name="friendship" required="" id="id_friendship">
                    {% for f in form.friendship.field.choices %}
                        {% if f.0 == room_chat.friendship1.id or f.0 == room_chat.friendship2.id  %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endif %}
                    {% endfor %}
                </select>
            </p>

            <p style="display: none;">
                <label for="id_sender">Sender:</label> 
                <select name="sender" required="" id="id_sender">
                    {% for f in form.sender.field.choices %}
                        {% if f.0 == request.user.id %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endif %}
                    {% endfor %}
                </select>
            </p>

             <div class="border-t-2 border-gray-200 px-4 pt-4 mb-2 sm:mb-0 ">
                <div class="relative flex w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-5 bg-gray-200 rounded-full pt-2 " style="height: 80px;">
                    <p class="mb-5">
                    <label style="display: none;" for="id_text">Text:</label> 
                    <textarea 
                        class="w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-full py-3 "
                        style="resize:none; height: 60px;"
                        placeholder="Write Something"
                        name="text" 
                        cols="160" 
                        required="" 
                        id="id_text"></textarea>
                    </p>
                    
                    <div class="absolute right-0 items-center inset-y-0 hidden sm:flex">
                         <p>
                            <label style="display: none;" for="id_file">File:</label> 
                            <input type="file" name="file" id="id_file">
                        </p> 

                        <button type="submit" class="js-submit inline-flex items-center justify-center rounded-full h-12 w-12 transition duration-500 ease-in-out text-white bg-blue-500 hover:bg-blue-400 focus:outline-none ">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-6 w-6 transform rotate-90">
                                <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z"></path>
                            </svg>
                        </button>
                    </div>
                </div>
            </div> 
        </form>
    <div class=" p:2 flex flex-col h-screen overflow-y-auto">
        <div id="posts" data-url="{% url 'get_message' room_chat.id %}" class="getEveything">
            
            {% for mes in my_chat_friend %}
                {% comment %} <div data-focus="focused"> 
                    {{mes.text}}
                </div> {% endcomment %}
                {% if mes.sender_id == request.user.id %}
                    <div id='messages' class='myPost flex flex-col space-y-4 p-3 scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch'>
                        <div class='chat-message'>
                            <div class='flex items-end'>
                                <div class='flex flex-col  text-xs  mx-2 order-2 items-start'>
                                    <div>
                                        <span class=' px-4 py-2 rounded-lg inline-block rounded-bl-none bg-gray-300 text-gray-600'>
                                            {{mes.text}}
                                            {% if mes.file %}
                                            <a href='/media/" + {{mes.file}} + "'>
                                                <div>
                                                    {{mes.file}}
                                                </div
                                            ></a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                                    <img src='https://static.wikia.nocookie.net/caramella-girls/images/9/99/Blankpfp.png/revision/latest?cb=20190122015011' alt='My profile' class='w-6 h-6 rounded-full order-1'>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div id='messages' data-focus='focused' class=' friendPost noFocus flex flex-col space-y-4 p-3 scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch justify-end'>
                        <div class='chat-message'>
                            <div class='flex justify-end'
                            ><div class='flex flex-col space-y-2 text-xs max-w-xs mx-2 order-1 justify-items-end'>
                                <div>
                                    <span class='px-4 py-2 rounded-lg inline-block rounded-br-none bg-blue-600 text-white '>
                                        {{mes.text}}
                                        {% if mes.file %}
                                            <a href='/media/" + {{mes.file}} +"'class='text-white' >
                                                <div>
                                                    {{mes.file}}
                                                </div
                                            ></a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                                    <img src='https://static.wikia.nocookie.net/caramella-girls/images/9/99/Blankpfp.png/revision/latest?cb=20190122015011' alt='My profile' class='w-6 h-6 rounded-full order-2'>
                                </div>
                            </div>
                        </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

<script>

</script> 

ChatOnline/Chat/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
     <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
     <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> 
    <title class="titleNoRead" data-sender="sender">{% block title %} Home {% endblock title %}</title>
</head>
<body>
    <nav class="bg-indigo-900 flex justify-between items-center border-b-2 border-gray-800 p-2 font-semibold text-white">
        <a class="no-underline text-white" href="{% url 'homePage' %}"><h1 class="text-3xl font-extrabold">WebChat</h1></a>
        <div class="input flex items-center">
            <form method="POST">
                {% csrf_token %} 
                <div class="flex justify-center">
                    <input
                        style="width: 500px; border: 1px solid black;"
                        name = "search"
                        type="search"
                        placeholder="Search Users..."
                        class=" w-full focus:outline-none pl-7  bg-gray-200 opacity-40 text-opacity-100 text-gray-400 rounded p-1  bg-white"
                    />
                    <button type="submit" class="py-3 px-6 text-white rounded-lg bg-green-500 shadow-lg" style="border: 1px solid black">Search</button>
                </div>
            </form>
        </div>
    
      {% if request.user.is_authenticated %}  
      <div class="flex">
          <a class="no-underline text-white" href="{% url 'account_logout' %}"><h5>Log out</h5></a>
        </div>
      {% else %}
        <div class="flex">
          <a class="no-underline text-white mr-2"  href="{% url 'account_login' %}"><h5>Login</h5></a>
          <a class="no-underline text-white" href="{% url 'account_signup' %}"><h5>Sign Up</h5></a>
        </div>
      {% endif %}
    </nav>


    
  <div style="width: 100%; height: 100%;" class="flex justify-center">
    {% if request.user.is_authenticated %}    
          <div class=" w-2/12 p-2 flex  justify-center" style="border-right: 1px solid black;">
            <div class="Top Section ml-4 align-middle">
              <div class=" flex items-center space-x-4 mt-2 ">
                {% comment %} <a href="{% url 'homePage' %}">
                  <img
                  src="https://static.wikia.nocookie.net/caramella-girls/images/9/99/Blankpfp.png/revision/latest?cb=20190122015011"
                  alt=""
                  class="w-20 h-10 rounded-full "
                />
                </a> {% endcomment %}
            
                <div>
                  <h3 class="font-bold">{{request.user.first_name}} {{request.user.last_name}} {{request.user.username}}</h3>
                  <div class="flex space-x-2">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="h-5 w-5 text-gray-600"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
                        clip-rule="evenodd"
                      />
                    </svg>
                          <p class="text-gray-400 font-semibold flex">
                            <a class="no-underline text-gray-900" href='{% url "see_profile"  request.user.id%}'>
                              @ID: {{request.user.id}} 
                            </a>
                          </p>
                  </div>
                </div>
              </div>

            
              <div class="footer-Section">
              {% if request.user.is_staff == True %}
                <div class="flex space-x-2 text-gray-500 cursor-pointer font-semibold hover:text-gray-700 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clip-rule="evenodd"
                    />
                  </svg>
                  <h5>
                          Staff Status
                  </h5>
                </div>
              {% endif %}
              {% if request.user.is_superuser == True %}
                <div class="flex space-x-2 text-gray-500 cursor-pointer font-semibold hover:text-gray-700 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clip-rule="evenodd"
                    />
                  </svg>
                  <h5>
                          Super User
                  </h5>
                </div>
              {% endif %}
                <div class="flex space-x-2 text-gray-500 cursor-pointer font-semibold hover:text-gray-700 ">
                  <span  class="h-5 w-5"><i class="bx bxs-user-account"></i></span>
                  <h5>
                      User
                  </h5>
                </div>
              </div>
            </div>
          </div> 
    {% endif %}

    {% block content %}
    <div style="width: 100%;" class="flex flex-col">
      {% if request.user.is_authenticated %}   
          <div class="flex h-screen  ">
            <div class="flex flex-col" style="width: 100%;">
                <div class="justify-center flex">
                    <h1 class="text-3xl font-extrabold m-2 underline">My friends:</h1>
                </div>
                    {% for friend in room_chat %}
                        <div class="bg-gray-100 justify-center flex m-5">
                            <div class="space-y-10 ">
                                <div class="flex flex-col items-center p-6 space-x-6 bg-white rounded-xl shadow-lg hover:shadow-xl transform                 hover:scale-105     transition duration-500" style="border: 1px solid black">
                                    {% if friend.friendship1.user1 == request.user %}
                                        <div class="flex justify-center bg-gray-100 p-4 w-72 space-x-4 rounded-lg">
                                                {{friend.friendship1.user2.first_name}} {{friend.friendship1.user2.last_name}} {{friend.friendship1.user2.username}}
                                        </div>
                                        <a href = "{% url 'see_profile' friend.friendship1.user2.id %}" class="flex justify-center py-3 px-6 text-white rounded-lg bg-green-500 shadow-lg" style="border: 1px solid black">
                                            <span>    
                                                Go to profile!
                                            </span>
                                        </a>
                                    {% elif friend.friendship1.user2 == request.user %}
                                        <div class="flex justify-center  bg-gray-100 p-4 w-72 space-x-4 rounded-lg">
                                            {{friend.friendship1.user1.first_name}} {{friend.friendship1.user1.last_name}} {{friend.friendship1.user1.username}}
                                        </div>
                                        <a href = "{% url 'see_profile' friend.friendship1.user2.id %}" class="py-3 px-6 text-white rounded-lg bg-green-500 shadow-lg" style="border: 1px solid black">
                                            <span>    
                                                Go to profile!
                                            </span>
                                        </a>
                                    {% endif %}
                                    <a href = "{% url 'chat_messages' friend.id %}" class="py-3 px-6 text-white rounded-lg bg-green-500 shadow-lg" style="border: 1px solid black">
                                        <span>    
                                            Go to chat!
                                        </span>
                                    </a>

                                  <div class="notification">
                                      
                                  </div>  
                                </div>
                                
                            </div>
                        </div>
                    {% endfor %}
            </div>    
          </div> 
      {% else %}
          <div style="margin:0;">    
            <div class="w-full h-screen bg-center bg-no-repeat bg-cover" style="background-image: url('https://images.unsplash.com/photo-1609342475528-dd7d93e8311e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=676&q=80');">
              <div class="w-full h-screen bg-opacity-50 bg-black flex justify-center items-center">
                <div class="mx-4 text-center text-white">
                  <h1 class="font-bold text-6xl mb-4">Welcome!</h1>
                  <a href="{% url 'account_login' %}" class="bg-red-500 rounded-md font-extrabold text-white text-center px-3 py-3 transition duration-300 ease-in-out hover:bg-red-600 mr-2 text-xl" >
                      Log in!
                  </a>
                  <a class="my-10 bg-white rounded-md font-extrabold text-black text-center px-3 py-3 transition duration-300 ease-in-out hover:bg-red-600  text-xl" style="width: 50px;">
                      or
                  </a>
                  <a href="{% url 'account_signup' %}" class="bg-red-500 rounded-md font-extrabold text-white text-center px-3 py-3 transition duration-300 ease-in-out hover:bg-red-600 ml-2 text-xl" >
                      Sign up!
                  </a>
                </div>
              </div>
            </div>
          </div>
      {% endif %}
    </div>
    {% endblock content %}
  </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/main.js' %}"></script>
        
</body>
</html>

ChatOnline/Chat/templates/profile.html
{% extends 'home.html' %}

{% block title %}Profile: {{profile.first_name}} {{profile.last_name}}{% endblock title %}

{% block content %}

{% if request.user.is_authenticated %}
<div style="width: 100%;">
    <div class="justify-center flex">
        <h1 class="text-3xl font-extrabold m-2 underline">Profile:</h1>
    </div>
    <div class="bg-gray-100 justify-center flex m-5" >
        <div class="space-y-10 ">
            <div class="flex items-center p-6 space-x-6 bg-white rounded-xl shadow-lg hover:shadow-xl transform hover:scale-105 transition duration-500" style="border: 1px solid black">
            <div class="flex bg-gray-100 p-4 w-72 space-x-4 rounded-lg">
                {{profile.first_name}} {{profile.last_name}} {{profile.username}}
            </div>
                
            <button type="submit " class="py-3 px-6 text-white rounded-lg bg-green-500 shadow-lg js-add-friend" style="border: 1px solid black"
            data-username = "{{profile.username}}" data-action="{% if  you_add %}Unfriend{% else %}Add Friend{% endif %}" data-url="{% url 'add_friend' profile.username %}">
                <span>
                    {% if you_add %}
                        Unfriend
                    {% else %}
                        Add Friend
                    {% endif %}
                </span>
            </button> 
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}