RebagTask2/GiftCard/urls.py
from django.contrib import admin
from django.urls import include, path


from feed.views import home, card_list, displayCards, add_gift_card, add_order_form, order_list, order_detail, edit_order_form, get_order_history, get_order_history_template, admin_gift_card_user_post, admin_gift_card, admin_gift_card_user_edit, admin_gift_card_user_delete, admin_zone_page, admin_display_gc, admin_manipulate_a_gc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('admin_zone/', admin_zone_page, name = "admin_zone_page"),
    path('card_list/', card_list, name="card_list"),
    path('order_list/', order_list, name="order_list"),
    path('admin_gift_card_user_post/', admin_gift_card_user_post, name="admin_gift_card_user_post"),
    path('admin_gift_card_user_edit/', admin_gift_card_user_edit, name="admin_gift_card_user_edit"),
    path('admin_gift_card_user_delete/', admin_gift_card_user_delete, name="admin_gift_card_user_delete"),
    path('admin_display_gc/', admin_display_gc, name="admin_display_gc"),
    path('admin_gift_card/', admin_gift_card, name="admin_gift_card"),
    path('add_gift_card/', add_gift_card, name="add_gift_card"),
    path('admin_manipulate_a_gc/<int:pk>', admin_manipulate_a_gc, name="admin_manipulate_a_gc"),
    path('order_detail/<int:pk>', order_detail, name="order_detail"),
    path('add_order/<int:pk>', add_order_form, name="add_order_form"),
    path('edit_order/<int:pk>', edit_order_form, name="edit_order_form"),
    path('order_history/<int:pk>', get_order_history, name="get_order_history"),
    path('allOrders/<int:pk>', get_order_history_template, name="get_order_history_template"),
    path('displayCards/', displayCards, name="displayCards"),
    # path('generate_token/', generateToken, name="generateToken"),
    path('', include('allauth.urls')),
]

RebagTask2/feed/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from rest_framework.authtoken.models import Token


class GiftCard(models.Model):
    name = models.CharField(max_length=200)
    available = models.BooleanField()

    def __str__(self):
        return  f'{self.id} {self.name}'

class UserGiftCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    giftCard = models.ForeignKey(GiftCard, on_delete=models.CASCADE, related_name="giftCard")
    amount = models.DecimalField(max_digits=19, decimal_places=2)

    class Meta:
        unique_together=[['user', 'giftCard']]

    def __str__(self):
        return  f'{self.id} {self.user.username} {self.giftCard.name}'

class Order(models.Model):
    giftCard = models.ForeignKey(UserGiftCard, on_delete=models.CASCADE, related_name="giftCardName")
    productOrdered = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=19, decimal_places=2)
    date = models.DateTimeField()
    orderNumber = models.CharField(max_length=200)

    def __str__(self):
        return  f'{self.id} {self.giftCard.user.username} {self.giftCard.giftCard.name}'

class OrderHistory(models.Model):
    giftCard = models.ForeignKey(UserGiftCard, on_delete=models.CASCADE, related_name="giftCardName2")
    logHistory = ArrayField(ArrayField(models.CharField(max_length=200), blank=True), blank=True)

    def __str__(self):
        return  f'{self.id} {self.giftCard.user.username} {self.giftCard.giftCard.name}'

@receiver(post_save, sender=UserGiftCard)
def create_order_history(sender, instance, created, **kwargs):
    if created :
        OrderHistory.objects.create(giftCard = instance, logHistory=[]) 

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)        

RebagTask2/GiftCard/templates/admin_zone/admin_display_gc.html
{% extends 'home.html' %}

{% block body %}

{% if request.user.is_staff %}
    <div class="mb-4 flex justify-center">
        <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">Gift Cards</div>
    </div>
    <div id="displayCards" class="flex flex-wrap p-2 justify-evenly" >
    {% for cgc in collectGC %}
            <div class="inline-block border-black border-2 border-solid rounded-lg p-4 bg-yellow-200">
                <div class="border-black border-b-2 border-solid  p-2 ">
                    <div class="flex justify-center text-xl font-bold">&bull;Card Name:</div>
                    <div class="flex justify-center text-xl font-bold text-blue-500">{{cgc.name}}</div>
                </div>
                <div class="border-black border-t-2 border-solid p-2 ">
                    <div class="flex justify-center text-xl font-bold">&bull;Available:</div>
                    <div class="flex justify-center text-xl font-bold text-blue-500">{{cgc.available}}</div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

{% endblock body %}

RebagTask2/GiftCard/templates/admin_zone/admin_gift_card_user_delete.html
{% extends 'home.html' %}

{% block title %}Delete Gift Cards{% endblock title %}
{% block body %}
<div class="mt-8 flex justify-center">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">}Delete Gift Cards</div>
</div>
{% if request.user.is_staff %}
    <div class="flex justify-center order" >
        <div class="p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg w-max "> 
            <form action="" method="" >
                {% csrf_token %}
                <p>
                    <div>
                        <label for="id_user">User:</label>
                    </div>
                    <select class="admin-user-delete" name="user" required="" id="id_user" multiple>
                        {% for f in form.user.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>
                
                <p>
                    <label for="id_giftCard">GiftCard:</label>
                    <select class="admin-giftCard-delete" name="giftCard" required="" id="id_giftCard">
                        {% for f in form.giftCard.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>

                <p class="flex justify-center">
                    <button class="font-bold border-2 border-solid border-gray-400 rounded-lg p-2 text-2xl bg-yellow-400 js-admin-delete-giftCard" type="submit" data-url="{% url 'admin_gift_card' %}" data-token="{{token}}">Submit</button>
                </p> 

                <p class="w-max text-xl mt-4 text-red-500 errors-delete-admin-giftCard">
            
                </p>
            </form>
        </div>
    </div>
{% endif %}

{% endblock body %}

RebagTask2/GiftCard/templates/admin_zone/admin_gift_card_user_edit.html
{% extends 'home.html' %}

{% block title %}Edit Gift Cards{% endblock title %}
{% block body %}
<div class="mt-8 flex justify-center">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">Edit Gift Cards</div>
</div>
{% if request.user.is_staff %}
    <div class="flex justify-center order" >
        <div class="p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg w-max "> 
            <form action="" method="PUT" >
                {% csrf_token %}
                <p>
                    <div>
                        <label for="id_user">User:</label>
                    </div>
                    <select class="admin-user-edit" name="user" required="" id="id_user" multiple>
                        {% for f in form.user.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>
                
                <p>
                    <label for="id_giftCard">GiftCard:</label>
                    <select class="admin-giftCard-edit" name="giftCard" required="" id="id_giftCard">
                        {% for f in form.giftCard.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>

                <p>
                    <label for="id_amount">Amount:</label>
                    <input class="admin-amount-edit" type="number" name="amount" step="0.01" required="" id="id_amount">
                </p>

                <p class="flex justify-center">
                    <button class="font-bold border-2 border-solid border-gray-400 rounded-lg p-2 text-2xl bg-yellow-400 js-admin-edit-giftCard" type="submit" data-url="{% url 'admin_gift_card' %}" data-token="{{token}}">Submit</button>
                </p> 

                <p class="w-max text-xl mt-4 text-red-500 errors-edit-admin-giftCard">
            
                </p>
            </form>
        </div>
    </div>
{% endif %}

{% endblock body %}

RebagTask2/GiftCard/templates/admin_zone/admin_gift_card_user_post.html
{% extends 'home.html' %}

{% block title %}Add Gift Cards{% endblock title %}
{% block body %}
<div class="mt-8 flex justify-center">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">Add Gift Cards</div>
</div>
{% if request.user.is_staff %}
    <div class="flex justify-center order" >
        <div class="p-2 font-bold bg-red-100 m-10 border-2 border-solid border-black rounded-lg w-max "> 
            <form action="" method="POST" >
                {% csrf_token %}
                <p>
                    <div>
                        <label for="id_user">User:</label>
                    </div>
                    <select class="admin-user-add" name="user" required="" id="id_user" multiple>
                        {% for f in form.user.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>
                
                <p>
                    <label for="id_giftCard">GiftCard:</label>
                    <select class="admin-giftCard-add" name="giftCard" required="" id="id_giftCard">
                        {% for f in form.giftCard.field.choices %}
                            <option value="{{f.0}}" >{{f.1}}</option> 
                        {% endfor %}
                    </select>
                </p>

                <p>
                    <label for="id_amount">Amount:</label>
                    <input class="admin-amount-add" type="number" name="amount" step="0.01" required="" id="id_amount">
                </p>

                <p class="flex justify-center">
                    <button class="font-bold border-2 border-solid border-gray-400 rounded-lg p-2 text-2xl bg-yellow-400 js-admin-add-giftCard" type="submit" data-url="{% url 'admin_gift_card' %}" data-token="{{token}}">Submit</button>
                </p> 

                <p class="w-max text-xl mt-4 text-red-500 errors-add-admin-giftCard">
            
                </p>
            </form>
        </div>
    </div>
{% endif %}

{% endblock body %}

RebagTask2/GiftCard/templates/admin_zone/admin_zone.html
{% extends 'home.html' %}

{% block body %}
<div class=" flex justify-center">
    <div class="no-underline text-3xl font-extrabold text-red-900 border-2 border-red-600 p-2 rounded-lg bg-pink-200">ADMIN ZONE</div>
</div>

<div class="flex">
    <div class="w-1/2 flex flex-col items-center">
        <div class="mt-10" >
            <a class="border-solid border-black border-2 rounded-lg font-bold text-xl text-blue-600 p-5 bg-green-400 " href="{% url 'add_gift_card' %}">Add a gift card in the database</a>
        </div>
        <div class="mt-20" >
            <a class="border-solid border-black border-2 rounded-lg font-bold text-xl text-blue-600 p-5 bg-green-400 " href="{% url 'admin_display_gc' %}">Show the gift cards from DB</a>
        </div>
    </div>
    <div class="w-1/2 flex flex-col items-center">
        <div class="mt-10" >
            <a class="border-solid border-black border-2 rounded-lg font-bold text-xl text-blue-600 p-5 bg-green-400 " href="{% url 'admin_gift_card_user_post' %}">Give a Gift card to multiple users</a>
        </div>
        <div class="mt-20">
            <a class="border-solid border-black border-2 rounded-lg font-bold text-xl text-blue-600 p-5 bg-green-400 " href="{% url 'admin_gift_card_user_edit' %}">Edit a Gift card amount to multiple users</a>
        </div>
        <div class="mt-20" >
            <a class="border-solid border-black border-2 rounded-lg font-bold text-xl text-blue-600 p-5 bg-green-400 " href="{% url 'admin_gift_card_user_delete' %}">Delete a Gift card to multiple users</a>
        </div>
    </div>
</div>
    
{% endblock body %}